# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(to='departments.Departments'),
        ),
    ]
