# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dashboardwidgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('view_users', 'Can view users'), ('add_users', 'Can add users'), ('change_users', 'Can change users'), ('delete_users', 'Can delete users'), ('suspend_users', 'Can suspend users')),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='dashboardcol1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dashboardcol2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
