# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 08:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from libs.user import createadminuser


def createadminuserifrequired(apps, schema_editor):
    ConfComponent = apps.get_model('config', 'ConfComponent')
    dircomp = ConfComponent.objects.filter(type='D').count()
    if dircomp > 0:
        adminuser = User.objects.filter(username='admin').count()
        if adminuser == 0:
            createadminuser()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_permissions'),
    ]

    operations = [
        migrations.RunPython(createadminuserifrequired),
    ]
