# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fileindex', models.IntegerField(blank=True, default=0, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('deltaseq', models.SmallIntegerField(blank=True, null=True)),
                ('markid', models.IntegerField(blank=True, null=True)),
                ('lstat', models.TextField(blank=True, null=True)),
                ('md5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fileset',
            fields=[
                ('filesetid', models.AutoField(primary_key=True, serialize=False)),
                ('fileset', models.TextField()),
                ('md5', models.TextField()),
                ('createtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'fileset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.TextField()),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=1)),
                ('level', models.CharField(max_length=1)),
                ('jobstatus', models.CharField(max_length=1)),
                ('schedtime', models.DateTimeField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('realendtime', models.DateTimeField(blank=True, null=True)),
                ('jobtdate', models.BigIntegerField(blank=True, null=True)),
                ('volsessionid', models.IntegerField(blank=True, null=True)),
                ('volsessiontime', models.IntegerField(blank=True, null=True)),
                ('jobfiles', models.IntegerField(blank=True, null=True)),
                ('jobbytes', models.BigIntegerField(blank=True, null=True)),
                ('readbytes', models.BigIntegerField(blank=True, null=True)),
                ('joberrors', models.IntegerField(blank=True, null=True)),
                ('jobmissingfiles', models.IntegerField(blank=True, null=True)),
                ('poolid', models.IntegerField(blank=True, null=True)),
                ('priorjobid', models.IntegerField(blank=True, null=True)),
                ('purgedfiles', models.SmallIntegerField(blank=True, null=True)),
                ('hasbase', models.SmallIntegerField(blank=True, null=True)),
                ('hascache', models.SmallIntegerField(blank=True, null=True)),
                ('reviewed', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('filetable', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobhisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('job', models.TextField()),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=1)),
                ('level', models.CharField(max_length=1)),
                ('jobstatus', models.CharField(max_length=1)),
                ('schedtime', models.DateTimeField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('realendtime', models.DateTimeField(blank=True, null=True)),
                ('jobtdate', models.BigIntegerField(blank=True, null=True)),
                ('volsessionid', models.IntegerField(blank=True, null=True)),
                ('volsessiontime', models.IntegerField(blank=True, null=True)),
                ('jobfiles', models.IntegerField(blank=True, null=True)),
                ('jobbytes', models.BigIntegerField(blank=True, null=True)),
                ('readbytes', models.BigIntegerField(blank=True, null=True)),
                ('joberrors', models.IntegerField(blank=True, null=True)),
                ('jobmissingfiles', models.IntegerField(blank=True, null=True)),
                ('poolid', models.IntegerField(blank=True, null=True)),
                ('priorjobid', models.IntegerField(blank=True, null=True)),
                ('purgedfiles', models.SmallIntegerField(blank=True, null=True)),
                ('hasbase', models.SmallIntegerField(blank=True, null=True)),
                ('hascache', models.SmallIntegerField(blank=True, null=True)),
                ('reviewed', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('filetable', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobhisto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('logtext', models.TextField()),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('pathid', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('view_jobs', 'Can view jobs'), ('add_jobs', 'Can add files jobs'), ('change_jobs', 'Can change jobs'), ('advanced_jobs', 'Can change jobs advanced'), ('delete_jobs', 'Can delete jobs'), ('run_jobs', 'Can run jobs'), ('restore_jobs', 'Can restore jobs'), ('cancel_jobs', 'Can cancel running jobs'), ('stop_jobs', 'Can stop running jobs'), ('restart_jobs', 'Can restart failed jobs'), ('comment_jobs', 'Can comment jobs'), ('view_datalocation', 'Can view jobs data location'), ('delete_jobid', 'Can delete jobs history'), ('status_jobs', 'Can view running job status')),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('jobstatus', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('jobstatuslong', models.TextField(blank=True, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
    ]
