# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-03 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'managed': False, 'permissions': (('view_jobs', 'Can view jobs'), ('add_jobs', 'Can add files jobs'), ('add_jobs_vmware', 'Can add VMware Guest jobs'), ('add_jobs_proxmox', 'Can add Proxmox Guest jobs'), ('add_jobs_xen', 'Can add XenServer Guest jobs'), ('add_jobs_kvm', 'Can add KVM Guest jobs'), ('add_jobs_hyperv', 'Can add Hyper-V Guest jobs'), ('add_jobs_rhev', 'Can add RHEV Guest jobs'), ('add_jobs_docker', 'Can add Docker container jobs'), ('change_jobs', 'Can change jobs'), ('advanced_jobs', 'Can change jobs advanced'), ('delete_jobs', 'Can delete jobs'), ('run_jobs', 'Can run jobs'), ('restore_jobs', 'Can restore jobs'), ('cancel_jobs', 'Can cancel running jobs'), ('stop_jobs', 'Can stop running jobs'), ('restart_jobs', 'Can restart failed jobs'), ('comment_jobs', 'Can comment jobs'), ('view_datalocation', 'Can view jobs data location'), ('delete_jobid', 'Can delete jobs history'), ('status_jobs', 'Can view running job status'))},
        ),
    ]
