language: python
python:
- 2.7
services: postgresql
env:
  global:
  - DJANGO="1.11"
  - DJANGO_SETTINGS_MODULE="ibadmin.settings"
  - PYTHONPATH="$HOME/builds/inteos/IBAdmin"
  - PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE bacula;" -U postgres
- psql -c "CREATE user bacula;" -U postgres
script:
- python manage.py migrate --noinput
- python manage.py check --fail-level ERROR
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: NMjme6+4pYUwfBcleiq2jjT1BrIFOHjfQCoVYgnxBmH/K2OlUId8oUR2zKj5i8idk6Iosu8sufELklh5D0B/ZCZxpZUWVoFoxW6co4IQySabHiiwuXhSzyd911J/PMsQ/wBxodSEu+7/aRxnk7h8YfOzI1+CksDqnSENaonVgSpRcmg14diMcFYLpB7zuJ911HrQDoeQDl48MJ9AipmSSEwjIljqyPkv5Kse/JVRIGgpFzLNEG/rrmlNJtfByT0LkiJ1t6Exp3gQkcWsAAxjKv0E4taSHgioD0mof87cyrJ1hG07hmZ8Y/YbrW9FYS+jogqIbXrSR0W15N/f+SblcH/JJOqpsmcY5ujX+eJEz9QUXUyL3XDMeWiW5MJIK2WWpVqSfC5tnqITkjBDtfFCxc7caKUKJDMWXBfQRsGt7bsR8exyL9XcAT/9QYhPWvTQbBEz2FWkH1otFreqOG+25UDYMoMCRZ3QbPymqlD9FN+JGg022u9gNw/N+tUPoAo7jTTH7MbRXhM7q+AdQOx5c4GwicovMDPLbZbWBd3lpkFBPGl2z8mNPByPS1WT+KKSKikByXb+N5J8isf1+Ht//4uPLGCPjpQl1+ErhSI62fH7BIC+vUnWbx9fz+DtzvDUcJfFuvYNbxczvBHw11DN82GDRekrv8Hc02Zl/fIuRTM=
