# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('nvalue', models.BigIntegerField(blank=True, null=True)),
                ('fvalue', models.FloatField(blank=True, null=True)),
                ('svalue', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatDataDays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('nvaluemin', models.BigIntegerField(blank=True, null=True)),
                ('nvaluemax', models.BigIntegerField(blank=True, null=True)),
                ('nvalueavg', models.BigIntegerField(blank=True, null=True)),
                ('fvaluemin', models.FloatField(blank=True, null=True)),
                ('fvaluemax', models.FloatField(blank=True, null=True)),
                ('fvalueavg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatDataHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('nvaluemin', models.BigIntegerField(blank=True, null=True)),
                ('nvaluemax', models.BigIntegerField(blank=True, null=True)),
                ('nvalueavg', models.BigIntegerField(blank=True, null=True)),
                ('fvaluemin', models.FloatField(blank=True, null=True)),
                ('fvaluemax', models.FloatField(blank=True, null=True)),
                ('fvalueavg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatParams',
            fields=[
                ('parid', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(max_length=1)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('chart', models.IntegerField(default=0)),
                ('display', models.IntegerField(default=1)),
                ('color', models.TextField(default='#000000')),
                ('box', models.TextField(default='box-primary')),
            ],
        ),
        migrations.CreateModel(
            name='StatDaterange',
            fields=[
                ('parid', models.OneToOneField(db_column='parid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.StatParams')),
                ('mintime', models.DateTimeField(auto_now_add=True)),
                ('maxtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatStatus',
            fields=[
                ('parid', models.OneToOneField(db_column='parid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.StatParams')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('nvalue', models.BigIntegerField(blank=True, null=True)),
                ('fvalue', models.FloatField(blank=True, null=True)),
                ('svalue', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='statdatahours',
            name='parid',
            field=models.ForeignKey(db_column='parid', on_delete=django.db.models.deletion.CASCADE, to='stats.StatParams'),
        ),
        migrations.AddField(
            model_name='statdatadays',
            name='parid',
            field=models.ForeignKey(db_column='parid', on_delete=django.db.models.deletion.CASCADE, to='stats.StatParams'),
        ),
        migrations.AddField(
            model_name='statdata',
            name='parid',
            field=models.ForeignKey(db_column='parid', on_delete=django.db.models.deletion.CASCADE, to='stats.StatParams'),
        ),
    ]
