# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statdata',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
