# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20180718_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('view_backup_stats', 'Can view backup statistics'), ('view_system_stats', 'Can view system statistics'), ('view_daemons_stats', 'Can view daemons statistics')),
            },
        ),
    ]
