# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'managed': False, 'permissions': (('view_backup_stats', 'Can view backup statistics'), ('view_system_stats', 'Can view system statistics'), ('view_daemons_stats', 'Can view daemons statistics'), ('view_job_stats', 'Can view job statistics'))},
        ),
    ]
