# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgets',
            name='height',
            field=models.IntegerField(default=189, null=True),
        ),
    ]
