# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vCenterHosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('thumbprint', models.CharField(max_length=64)),
            ],
        ),
    ]
