# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('view_vmware', 'Can view VMware objects'), ('view_proxmox', 'Can view Proxmox objects'), ('view_xen', 'Can view XenServer objects'), ('view_kvm', 'Can view KVM objects'), ('view_hyperv', 'Can view Hyper-V objects'), ('view_rhev', 'Can view RHEV objects'), ('add_vcenter', 'Can add VMware vCenter'), ('add_vmware', 'Can add VMware hosts'), ('add_proxmox', 'Can add Proxmox hosts'), ('add_xen', 'Can add XenServer hosts'), ('add_kvm', 'Can add KVM hosts'), ('add_hyperv', 'Can add Hyper-V hosts'), ('add_rhev', 'Can add RHEV hosts'), ('change_vcenter', 'Can edit VMware vCenter'), ('delete_vcenter', 'Can delete VMware vCenter'), ('list_vmware', 'Can list VMware guests'), ('list_vmware_hosts', 'Can list VMware ESX hosts'), ('list_proxmox', 'Can list Proxmox guests'), ('list_xen', 'Can list XenServer guests'), ('list_kvm', 'Can list KVM guests'), ('list_hyperv', 'Can list Hyper-V guests'), ('list_rhev', 'Can list RHEV guests')),
            },
        ),
        migrations.AddField(
            model_name='vcenterhosts',
            name='department',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
