# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('versionid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfComponent',
            fields=[
                ('compid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConfParameter',
            fields=[
                ('parid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1000)),
                ('str', models.BooleanField(default=False)),
                ('enc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfResource',
            fields=[
                ('resid', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('compid', models.ForeignKey(db_column='compid', on_delete=django.db.models.deletion.CASCADE, to='config.ConfComponent')),
            ],
        ),
        migrations.CreateModel(
            name='ConfRtype',
            fields=[
                ('typeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='confresource',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='config.ConfRtype'),
        ),
        migrations.AddField(
            model_name='confparameter',
            name='resid',
            field=models.ForeignKey(db_column='resid', on_delete=django.db.models.deletion.CASCADE, to='config.ConfResource'),
        ),
        migrations.AlterUniqueTogether(
            name='confcomponent',
            unique_together=set([('type', 'name')]),
        ),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (1, 'Director');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (2, 'Storage');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (3, 'FileDaemon');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (4, 'Client');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (5, 'Messages');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (6, 'Catalog');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (7, 'Schedule');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (8, 'Job');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (9, 'JobDefs');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (10, 'Fileset');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (11, 'Pool');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (12, 'Device');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (13, 'Autochanger');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (14, 'Include');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (15, 'Exclude');"),
        migrations.RunSQL("INSERT INTO config_confrtype (typeid, name) VALUES (16, 'Options');"),
    ]
