# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('proc', models.IntegerField(choices=[(1, 'Delete jobids for Job'), (2, 'Delete jobs and jobids for Client'), (3, 'Detect drives for Library')])),
                ('status', models.CharField(choices=[('N', 'New task'), ('R', 'Running task'), ('F', 'Finished succesfully task'), ('E', 'Finished with errors task')], default='N', max_length=1)),
                ('progress', models.IntegerField(default=0)),
                ('params', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
