# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170507_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tpid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='proc',
            field=models.IntegerField(choices=[(1, 'Delete jobids for Job'), (2, 'Delete jobs and jobids for Client'), (3, 'Detect drives for Library'), (4, 'Labeling tape volumes'), (5, 'Rescanning drives for Library')]),
        ),
    ]
