# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180811_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('N', 'New task'), ('R', 'Running task'), ('F', 'Finished succesfully task'), ('E', 'Finished with errors task'), ('C', 'Task canceled')], default='N', max_length=1),
        ),
    ]
