# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('view_roles', 'Can view roles'), ('add_roles', 'Can add roles'), ('change_roles', 'Can change roles'), ('delete_roles', 'Can delete roles')),
            },
        ),
    ]
