# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('shortname', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
