# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20170712_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('view_departments', 'Can view departments'), ('add_departments', 'Can add departments'), ('change_departments', 'Can change departments'), ('delete_departments', 'Can delete departments'), ('add_members', 'Can add memebers'), ('delete_members', 'Can delete members')),
            },
        ),
    ]
